language: node_js
node_js:
  - 16
cache:
  directories:
    - ~/.npm
install:
  - npm install
script:
  - npm run lint --workspaces
  - npm run test --workspaces
  - npm run build --workspace=frontend
  - npm run cdk -- deploy --all
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/build
  on:
    branch: main