language: node_js
node_js:
  - 16
cache:
  directories:
    - ~/.npm
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats python-pip python-setuptools
  - sudo pip install awscli
  - aws configure
install:
  - npm install
script:
  - npm run lint --workspaces
  - npm run test --workspaces
  - npm run build --workspace=frontend
  - npm run cdk -- bootstrap aws://129988434354/eu-central-1 --verbose
  # - npm run cdk -- deploy --all
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/build
  on:
    branch: main