language: node_js
node_js:
  - 16
cache:
  directories:
    - ~/.npm
before_install:
  - sudo apt-get install jq  # Install jq using apt-get
install:
  - npm install
script:
  - npm run lint --workspaces
  - npm run test --workspaces
  - npm run cdk -- deploy --all --outputs-file ./cdk-outputs.json
  - export REACT_APP_AWS_COGNITO_USER_POOL_ID=$(jq -r '.CognitoStack.userPoolId' cdk-outputs.json)
  - export REACT_APP_AWS_COGNITO_USER_POOL_APP_CLIENT_ID=$(jq -r '.CognitoStack.userPoolClientId' cdk-outputs.json)
  - npm run build --workspace=frontend
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/build
  on:
    branch: main