language: node_js
node_js:
  - 16
env:
 - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
 - AWS_ACCOUNT_NUMBER=$AWS_ACCOUNT_NUMBER
 - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
 - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
cache:
  directories:
    - ~/.npm
install:
  - npm install
script:
  - npm run lint --workspaces
  - npm run test --workspaces
  - npm run build --workspace=frontend
  - npm run cdk deploy -- --all
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/build
  on:
    branch: main