dist: bionic
language: node_js
node_js: 
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
install:
  - npm install
# Following Envs need to be set:
# AWS_ACCESS_KEY_ID, AWS_ACCOUNT_NUMBER, AWS_DEFAULT_REGION, AWS_SECRET_ACCESS_KEY, CDK_DEFAULT_ACCOUNT, CDK_DEFAULT_REGION
jobs:
  include:
    - stage: Lint
      name: Run lining rules
      script: 
        - npm run lint
    - stage: Test
      name: Running unit test
      script:
        - npm run test
    - stage: Deploy
      name: Deploy to AWS Cloud
      script:
        - npm run cdk deploy --all

after_failure:
  - cat dist/newman/report.json